spring.application.name=perito-service
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.jpa.open-in-view=false
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
