spring.application.name=andre-gaspar-microsservicos
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.batch.job.enabled=false
batch.atividades.arquivo=${BATCH_ATIVIDADES_ARQUIVO:classpath:dados/atividades-importacao.csv}
spring.jpa.open-in-view=false
integracoes.brasil-api.url=${BRASIL_API_URL:https://brasilapi.com.br}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
