spring.application.name=andre-gaspar-microsservicos
spring.jpa.open-in-view=false
integracoes.brasil-api.url=${BRASIL_API_URL:https://brasilapi.com.br}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
